import { useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

const guideSteps = [
  {
    number: "01",
    title: "Enter Target Parameters",
    badge: "Step 1",
    description: "Provide the Page URL you wish to analyze, your desired Anchor Text phrase, and the target destination Link URL.",
    details: [
      "Page URL: The blog post or article webpage where you want to insert a backlink.",
      "Anchor Text: The specific keyword or phrase you wish to hyperlink (e.g., 'best AI content tools').",
      "Anchor Link: The destination URL that the anchor text should point to (e.g., 'https://yoursite.com/ai-tools')."
    ]
  },
  {
    number: "02",
    title: "Automated Playwright Crawling",
    badge: "Step 2",
    description: "ATRF runs Playwright behind the scenes to fetch the target page, crawl associated internal links, and extract textual paragraphs.",
    details: [
      "Bypasses standard client rendering blocks with headless Chromium.",
      "Extracts main article headlines, section subheadings, and body content.",
      "Saves internal site hierarchy for deep contextual matching."
    ]
  },
  {
    number: "03",
    title: "AI Scenario Evaluation (Gemini 2.5)",
    badge: "Step 3",
    description: "The extracted text is sent to the FastAPI microservice. Gemini 2.5 Flash analyzes the text to pick the best placement scenario.",
    details: [
      "Classifies content against 4 distinct editorial link scenarios.",
      "Ensures tone consistency, syntactic harmony, and natural keyword flow.",
      "Selects exact preceding or target sentence for substitution or addition."
    ]
  },
  {
    number: "04",
    title: "Review Results & One-Click Copy",
    badge: "Step 4",
    description: "Instantly view the original text, the AI-modified sentence, and use the 1-click copy button to paste straight into your CMS.",
    details: [
      "Compare 'Before' vs 'After' sentence structure side-by-side.",
      "Copy formatted HTML hyperlinks (<a href='...'>anchor</a>) or plain text.",
      "Save history directly into your ATRF scan dashboard."
    ]
  }
];

const scenarioGuide = [
  {
    id: "SCENARIO_1",
    name: "Scenario 1: NEW PHRASE ADD",
    useCase: "Best when no existing sentence in the article directly discusses your topic.",
    action: "Inserts a brand-new contextual sentence containing the anchor text right AFTER a related paragraph line."
  },
  {
    id: "SCENARIO_2",
    name: "Scenario 2: PHRASE REPLACE",
    useCase: "Best when an existing sentence is too generic or weakly written.",
    action: "Replaces the weak sentence with a newly crafted, high-impact sentence including the anchor link."
  },
  {
    id: "SCENARIO_3",
    name: "Scenario 3: ALREADY EXISTED (Native Fit)",
    useCase: "Best when the article already contains the target phrase or keyword natively.",
    action: "Identifies the exact native text and wraps it in your target hyperlink without changing any words."
  },
  {
    id: "SCENARIO_4",
    name: "Scenario 4: PHRASE APPEND / MODIFY",
    useCase: "Best when an existing sentence can be easily expanded with a secondary clause.",
    action: "Appends a new descriptive phrase or clause containing your anchor link to the end of an existing sentence."
  }
];

function GuidePage() {
  const { isAuthenticated } = useAuth();
  const [copiedExample, setCopiedExample] = useState(false);

  const sampleBefore = "Digital publishers are focusing on search intent and topical authority in 2026.";
  const sampleAfter = "Digital publishers are focusing on search intent and topical authority in 2026. Leveraging <a href='https://myagency.com/seo-suite'>modern SEO suites</a> ensures long-term organic growth.";

  const handleCopyExample = () => {
    navigator.clipboard.writeText(sampleAfter);
    setCopiedExample(true);
    setTimeout(() => setCopiedExample(false), 2000);
  };

  const analyzerTarget = isAuthenticated ? "/dashboard" : "/login";

  return (
    <div className="guide-content">
      {/* Page Hero */}
      <section className="hero-section guide-hero">
        <span className="eyebrow">User Guide & Documentation</span>
        <h1 className="hero-title">How To Run ATRF & Optimize Link Placement</h1>
        <p className="hero-subtitle">
          Follow this simple guide to master AI-driven editorial backlink insertion,
          understand scenario recommendations, and streamline your workflow.
        </p>
      </section>

      {/* Worked Example Showcase */}
      <section className="landing-section">
        <div className="section-header">
          <span className="eyebrow">Interactive Example</span>
          <h2>Real-World Analysis Breakdown</h2>
          <p>Here is an example input and the resulting output generated by ATRF:</p>
        </div>

        <div className="guide-example-card">
          <div className="example-inputs">
            <h3>1. Submitted Input Form</h3>
            <div className="input-pills">
              <div className="input-pill">
                <span className="label">Target Page URL:</span>
                <code>https://techblog.com/seo-trends-2026</code>
              </div>
              <div className="input-pill">
                <span className="label">Anchor Text:</span>
                <strong className="highlight">modern SEO suites</strong>
              </div>
              <div className="input-pill">
                <span className="label">Target Link:</span>
                <code>https://myagency.com/seo-suite</code>
              </div>
            </div>
          </div>

          <div className="example-output">
            <div className="output-header">
              <h3>2. AI Recommended Scenario: <span className="badge-scenario">SCENARIO 1 (New Phrase Add)</span></h3>
            </div>

            <div className="example-comparison">
              <div className="box before-box">
                <span className="box-tag">Original Sentence from Target Page</span>
                <p>{sampleBefore}</p>
              </div>

              <div className="box after-box featured">
                <div className="box-tag-row">
                  <span className="box-tag highlighted">Transformed Output with Anchor Link</span>
                  <button className="copy-chip" onClick={handleCopyExample}>
                    {copiedExample ? "Copied HTML" : "Copy Result"}
                  </button>
                </div>
                <p dangerouslySetInnerHTML={{ __html: sampleAfter }} />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Step-by-Step Walkthrough */}
      <section className="landing-section">
        <div className="section-header text-center">
          <span className="eyebrow">4-Step Workflow</span>
          <h2>How The Analysis Process Works</h2>
          <p>From initial form submission to final CMS copy, ATRF executes 4 automated steps.</p>
        </div>

        <div className="guide-steps-container">
          {guideSteps.map((step) => (
            <article key={step.number} className="guide-step-card">
              <div className="step-header">
                <span className="step-number-tag">{step.number}</span>
                <span className="step-badge">{step.badge}</span>
              </div>
              <h3>{step.title}</h3>
              <p>{step.description}</p>
              <ul className="step-details-list">
                {step.details.map((detail, idx) => (
                  <li key={idx}>{detail}</li>
                ))}
              </ul>
            </article>
          ))}
        </div>
      </section>

      {/* Placement Scenarios Reference */}
      <section className="landing-section">
        <div className="section-header text-center">
          <span className="eyebrow">Placement Logic</span>
          <h2>Understanding The 4 Editorial Scenarios</h2>
          <p>ATRF dynamically selects the best scenario based on the contextual structure of your target article.</p>
        </div>

        <div className="scenarios-grid">
          {scenarioGuide.map((scenario) => (
            <div key={scenario.id} className="scenario-guide-card">
              <div className="scenario-header">
                <h4>{scenario.name}</h4>
              </div>
              <div className="scenario-body">
                <p><strong>When it is used:</strong> {scenario.useCase}</p>
                <p><strong>Action taken:</strong> {scenario.action}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Call to Action */}
      <section className="cta-banner">
        <h2>Ready To Run Your First Scan?</h2>
        <p>Analyze target URLs in seconds using ATRF.</p>
        <div className="cta-buttons">
          <Link to={analyzerTarget} className="primary-button cta-primary">
            Launch Analyzer
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="app-footer">
        <div className="footer-content">
          <div className="footer-brand">
            <span className="brand-mark">ATRF</span>
            <p>Anchor Text Replacement & Editorial Link Finder</p>
          </div>
          <div className="footer-links">
            <Link to="/">Home</Link>
            <Link to="/guide">User Guide</Link>
            <Link to={analyzerTarget}>Analyzer</Link>
          </div>
        </div>
        <div className="footer-bottom">
          <p>© {new Date().getFullYear()} ATRF. Built with React, Express, FastAPI & Gemini.</p>
        </div>
      </footer>
    </div>
  );
}

export default GuidePage;
